### ISSUE TITLE
Ensure caching covers tile requests with custom ES queries

### ISSUE THREAD

**Issue by manossaratsis** [StationA/tilenol#29]

**Comment by ccma14** [comment]
Looking at logs when testing `tilenol` for PR #31 indicates that this functions as expected.

Here is the code that we use to compute the cache key:

```
	key := r.URL.RequestURI()
```

Also logs indicate that the query part of the request is part of the key:

```
Key [/_all/16/10486/25327.mvt?s=name:name&s=center:centroid] is not cached
```

So this can likely be closed, because it works as intended.

**Comment by jerluc** [comment]
Good catch @ccma14 , thanks for double-checking!
